### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Kim-Mendoza3** [SistemasTecTlaxiaco/infografia-de-hilos-Kim-Mendoza3#2]
https://drive.google.com/file/d/1i7MiLKwstH506V0nSiNnfAYekWTbvQmk/view?usp=sharing

**Comment by HECTOR-KDM02** [comment]
20 Puntos

Todo esta correctamente estructurado pero se puede mejorar donde se ponen los titulos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
